# Generated by Django 5.0.7 on 2024-07-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_list_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='list',
        ),
    ]
