# Generated by Django 5.0.7 on 2024-07-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_tasks_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
